# Cloud NetTest Framework - Host Inventory
# Updated with working SSH connections
# Last updated: 2025-10-05

hosts:
  # AWS US-West-1 (California) - Oracle San Jose/Phoenix optimal probe
  - id: aws-us-west-1-probe01
    provider: aws
    region: us-west-1
    hostname: NetworkTest-USWest1
    instance_id: i-035a2165f45edc09c
    public_ip: 3.101.64.113
    private_ip: 172.31.23.26
    ssh_user: ubuntu
    ssh_key: ~/.ssh/network-testing-key-west.pem
    notes: "Best performance to Oracle San Jose (<1ms) and Phoenix (19ms)"
    capabilities:
      - icmp_ping
      - tcp_connect
      - https_timing
      - traceroute
      - mtr
      - dig
      - curl
    status: active
    last_verified: "2025-10-05T20:00:00Z"

  # AWS US-East-2 (Ohio) - Central balanced probe
  - id: aws-us-east-2-probe01
    provider: aws
    region: us-east-2
    hostname: NetworkTest-USEast2
    instance_id: i-0dfc6bdd6a24ca82e
    public_ip: 18.222.238.187
    private_ip: 172.31.44.171
    ssh_user: ubuntu
    ssh_key: ~/.ssh/network-testing-key-east2.pem
    notes: "Balanced central performance, good Ashburn backup (13.8ms)"
    capabilities:
      - icmp_ping
      - tcp_connect
      - https_timing
      - traceroute
      - mtr
      - dig
      - curl
    status: active
    last_verified: "2025-10-05T20:00:00Z"

  # Placeholder for Azure probes (to be added)
  # - id: azure-eastus-probe01
  #   provider: azure
  #   region: eastus
  #   ssh_user: azureuser

  # Placeholder for GCP probes (to be added)
  # - id: gcp-us-east1-probe01
  #   provider: gcp
  #   region: us-east1
  #   ssh_user: debian
